language: python
python:
- '2.7'
- '3.6'
install:
- pip install .
- pip install pyyaml
script:
- python run_tests.py
deploy:
  provider: pypi
  user: worvast
  password:
    secure: J3YPGEaDHD1H9pVQscrh4J2U18ptq8pM5UsjIKGe6WGlgiTMhR+WYRcdQSFIGSyKZMkdnLavSuvImcUzBSL6L3WqarRZ6HBgGXtxxHRVNmk96ZZlBN5qq0AUJzHN61x5JbG+OWzJMZE1HDo6zcD36KvaIAfKu3AyaEYeVes54PY5cLC/JH/HooOP0FS643kbttkiTYKmEajJiCgu/SiXH5dtfuz5GO0CXrEp0ww+FtcTmC9T9txyjS+IBIvbNPHJC9M5jg6bgu214fCIr5iGNZ8LQulRskBOsqhCRbyyWjuF0wgl3Dkefa0z3YJpl2KYHYW0bT0UY2J8WXnE66NT6js2sv/mNdcRAZjjzugcr9mr11FrLazIjNJwDwlSTtuNoys4E449wQZfQ4vUsUANwnsXQJAdujANS8O2Yuk65uIlgnNpYBxXI71OPYZ6dzhDOsAcwlUrS9jZi2+UWGtOXoZX3i3qLWwBHEASXNSN2WLZOVj3lTEyBB7WCbBqDANHCRLrkyHMrUkOP9ptE7lvATCVfHIO2axsaxNJRKHI6W53p+6uMRAt9u0LIKBB4hyZMo51j7xkq6uO4cQt2CINVU24gYajcalswtJ/Cr0onj26xx2g/xq19sU1L7rpp8OZGFnLPHptxV3ezTlhdk86ZfwOQI1TC4KPAQlRZARDeSk=
  on:
    tags: true
  distributions: "sdist bdist_wheel"
  skip_existing: true