language: python
python:
- '2.7'
- '3.5'
install:
- pip install .
- pip install pyyaml
script:
- python run_tests.py
deploy:
  - provider: pypi
    user: worvast
    password:
      secure: YdcpCoGTzy1bmjMQH/Lxw5ZdLAlUUHvE7fq2n84BNjz1XiCokpoCKkR1OEC3SGiMNtpy3lJ5YvdHtEzfqmO1mUrwlHT9TyTx/fiKnA5nTWNVxIYtHzhuSL1Z1lopQIHU6QS5FXCXM0ZWs/47X0N7pLKz9V8Pu0g+aeC91swHCEGGDICrEbXFTbMFvJxcHyEIXk2NQ1q0T6cupNOsomQlZfO75SVZMUv/VXp0RpIRfn3qp5Q3XsR6aWP43Jb9IH/4PLLpTfsJpU+1kIsqr55FKy1WTWA89W/E1oXnaf5UK3GbpNuE9qguZn+RwvnRWDg1txvQxJD3tfeKQ5EZqNhB9HbcaYr6USWeA4drE/mVZZePZEMBXT2NSEFEO2dCEMiBBY9feMeTYryJLFgwiHxkc/yM4RnzKLF3MGGcow5IKVpgJYcoNrMS+Mb5/HH8a5E0A+wwHpztCKtOGTV4dGzWsomIPS1kK3FlMTEE1z8bF5ISX9O9dh4P08Uh4YciNShY7GTNvPO13Z7S38YGbDQeijj/Q2SA66zq8vebh37xtJ6BSA54BBFjrkkOBxfi024fsCs30FXvASj8Q2Tkr120VxA5D3OKo29pgWy1357YyCQrWmiLlY3KM/z5XkM0s6hDprirBlquw9+euaoKTBgvJqFb0/pJnqB8E8FBLboKg+A=
    on:
      tags: true
      python: 3.5
    distributions: sdist bdist_wheel
    skip_existing: true
    skip_cleanup: true
  - provider: releases
    api_key:
      secure: pP/ky4BlJNU+tTEW0YSRzj92+CzM8upmnS6bIj4cLlV4crJXlrGs5PA4+07oaILLZxIRyeBR+VFXyebseCffyBPEVFC9GYsxUlq32F0p1HxX9w6LfK8Zf/FNQCdtcN62ahM3ZbuAQBftNtldQ885SwyjHVJo4ZUAjMvr4nB8+ZqAF8Oykgx0R24yVeq1N3TQbRF8nTbwcTgoXP37r0Pkuq6ljve3lV5SZi56a4h1aOSPxNAknBX9xz7Avv/NfgkZ7R+f+mk3juBZuPov02+3P7xHtCUi8yo/bNi96ufwXiWD9xZPjZDOK3owV9iwWR2E/MDcOpORvIh8Rim7i3kMx7vDOIDR3yyYR36FTh2DIbQVRLKxCix8uESxVy84DpaWEaCOzn0jx4ddD/+EGBVRTjWqddF3Pu5+cKFCx7BYKlIDNPtYq3fIfsUKqoA7OaqJAIbk5N+Fl6jaDbbui2FCZN8LymwzpOKHv68ILztDLGIDUd4u6NpJMMHjF4xdp1tSkLyVEIE9cmrWJFom4J2STh8Ji6bODUY2vNK2vvxohJ/Cp5qBXd4VvegZGQu6xmV8EBEtqHX7UO9uY308SIV9wtwSTKswJyoptkJLPgeFnA/gCdc26MFvfo5Lxo1Etx1W8nXJIfkMo103xEuybGW2U4A7KDcZXvjdnOR6oHKhtkE=
    file: dist/devo_sdk-*.whl
    on:
      repo: Devo/python-sdk
